expressions:
  - name: get-faidx-file-from-reference-file
    path: get-faidx-file-from-reference-file
    versions:
      - name: 1.0.0
        path: 1.0.0/get-faidx-file-from-reference-file__1.0.0.cwl
        md5sum: 5537a7433792c92e63c11abe20e9ba78
    categories: []
  - name: create-contig-obj-for-hla-chr6-region
    path: create-contig-obj-for-hla-chr6-region
    versions:
      - name: 1.0.0
        path: 1.0.0/create-contig-obj-for-hla-chr6-region__1.0.0.cwl
        md5sum: edd04eddfc2ad0985a68a3a5843d915c
    categories: []
  - name: get-samplesheet-midfix-regex
    path: get-samplesheet-midfix-regex
    versions:
      - name: 1.0.0
        path: 1.0.0/get-samplesheet-midfix-regex__1.0.0.cwl
        md5sum: 93d9dba10e7674e53a886ef28818c133
    categories: []
  - name: flatten-array-fastq-list
    path: flatten-array-fastq-list
    versions:
      - name: 1.0.0
        path: 1.0.0/flatten-array-fastq-list__1.0.0.cwl
        md5sum: 9c35f9205f9ce613b754f06f004b1de6
    categories: []
  - name: parse-int-array
    path: parse-int-array
    versions:
      - name: 1.0.0
        path: 1.0.0/parse-int-array__1.0.0.cwl
        md5sum: 0cbe7e9f567a4b6e18c9f8af6fc79bce
    categories: []
  - name: parse-int
    path: parse-int
    versions:
      - name: 1.0.0
        path: 1.0.0/parse-int__1.0.0.cwl
        md5sum: 54572449b52b935bb80007b224b0dd3e
    categories: []
  - name: parse-file
    path: parse-file
    versions:
      - name: 1.0.0
        path: 1.0.0/parse-file__1.0.0.cwl
        md5sum: 6b7a5626a907a0c97fd8b75e45760080
    categories: []
  - name: get-compressed-vcf-file-from-directory
    path: get-compressed-vcf-file-from-directory
    versions:
      - name: 1.0.0
        path: 1.0.0/get-compressed-vcf-file-from-directory__1.0.0.cwl
        md5sum: a0d6c8ea819df1701d5b8361df7015ce
    categories: []
  - name: get-custom-output-dir-entry-for-tso500-post-processing
    path: get-custom-output-dir-entry-for-tso500-post-processing
    versions:
      - name: 1.0.0
        path: 1.0.0/get-custom-output-dir-entry-for-tso500-post-processing__1.0.0.cwl
        md5sum: f5afc198579fa46d75969659d0680849
      - name: 2.0.1
        path: 2.0.1/get-custom-output-dir-entry-for-tso500-post-processing__2.0.1.cwl
        md5sum: f206bc87217a09ebaf647d955af484bf
    categories: []
  - name: get-bam-file-from-directory
    path: get-bam-file-from-directory
    versions:
      - name: 1.0.0
        path: 1.0.0/get-bam-file-from-directory__1.0.0.cwl
        md5sum: 6b3d67af802121ad5d6e5964b97e255c
    categories: []
  - name: create-predefined-mount-paths-and-umccrise-row-from-umccrise-schema
    path: create-predefined-mount-paths-and-umccrise-row-from-umccrise-schema
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/create-predefined-mount-paths-and-umccrise-row-from-umccrise-schema__1.2.1--0.cwl
        md5sum: 10900c8d1d5a71921ee4b5d23202287f
      - name: 1.2.2--0
        path: 1.2.2--0/create-predefined-mount-paths-and-umccrise-row-from-umccrise-schema__1.2.2--0.cwl
        md5sum: 7caaf4d0d7e50f97eda0b1404c905cdb
    categories: []
  - name: get-custom-output-dir-entry-for-tso500-with-post-processing
    path: get-custom-output-dir-entry-for-tso500-with-post-processing
    versions:
      - name: 2.0.1
        path: 2.0.1/get-custom-output-dir-entry-for-tso500-with-post-processing__2.0.1.cwl
        md5sum: dcecdce54ae1e4ff8e8206d77b166f41
    categories: []
