workflows:
  - name: optitype-pipeline
    path: optitype-pipeline
    versions:
      - name: 1.3.5
        path: 1.3.5/optitype-pipeline__1.3.5.cwl
        md5sum: 8a60ddcaa75b85884785de055320280f
    categories:
      - hla
  - name: get-hla-regions-bed
    path: get-hla-regions-bed
    versions:
      - name: 1.0.0
        path: 1.0.0/get-hla-regions-bed__1.0.0.cwl
        md5sum: fde83608bc8d0624b260cc2fb9609420
    categories: []
  - name: dragen-germline-pipeline
    path: dragen-germline-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-germline-pipeline__3.7.5.cwl
        md5sum: 9c415babb9da86131c01d4e816d9ef67
      - name: 3.9.3
        path: 3.9.3/dragen-germline-pipeline__3.9.3.cwl
        md5sum: 385a3d1c3be8b485585f920ad60b46b3
    categories:
      - dragen
  - name: dragen-qc-hla-pipeline
    path: dragen-qc-hla-pipeline
    versions:
      - name: 3.7.5--1.3.5
        path: 3.7.5--1.3.5/dragen-qc-hla-pipeline__3.7.5--1.3.5.cwl
        md5sum: 5380314a8aec7e17de1f2be6ce95e75b
    categories: []
  - name: tso500-ctdna
    path: tso500-ctdna
    versions:
      - name: 1.1.0--120
        path: 1.1.0--120/tso500-ctdna__1.1.0--120.cwl
        md5sum: 49a75e54a74e3b7920c972bec4d42bfb
    categories:
      - tso500
  - name: bcl-conversion
    path: bcl-conversion
    versions:
      - name: 3.7.5
        path: 3.7.5/bcl-conversion__3.7.5.cwl
        md5sum: c6f25b70a6ed2438d4480993d47fe5a9
    categories: []
  - name: dragen-somatic-pipeline
    path: dragen-somatic-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-somatic-pipeline__3.7.5.cwl
        md5sum: 90f8ccedf9d3566739425c519ed79d03
      - name: 3.9.3
        path: 3.9.3/dragen-somatic-pipeline__3.9.3.cwl
        md5sum: c22680a9504c885b0d1692f4448e96f9
    categories:
      - dragen
      - variant-calling
  - name: dragen-transcriptome-pipeline
    path: dragen-transcriptome-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-transcriptome-pipeline__3.7.5.cwl
        md5sum: 4695d5a6b43a53fc0767be3f18d2d4cd
      - name: 3.8.4
        path: 3.8.4/dragen-transcriptome-pipeline__3.8.4.cwl
        md5sum: 2666a32bab6e8bf1d9700aec27ff70f6
      - name: 3.9.3
        path: 3.9.3/dragen-transcriptome-pipeline__3.9.3.cwl
        md5sum: 8595a4852fe150f6c3e4137605aa2afb
    categories: []
  - name: dragen-alignment-pipeline
    path: dragen-alignment-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-alignment-pipeline__3.7.5.cwl
        md5sum: 7d1f53b5a952427be5dbcd1165795907
      - name: 3.9.3
        path: 3.9.3/dragen-alignment-pipeline__3.9.3.cwl
        md5sum: 7e729ce9fa6d4a7608f7119f9f48b79b
    categories:
      - alignment
      - dragen
  - name: dragen-wgs-qc-pipeline
    path: dragen-wgs-qc-pipeline
    versions:
      - name: 3.7.5
        path: 3.7.5/dragen-wgs-qc-pipeline__3.7.5.cwl
        md5sum: e8a5f7e0631cb9d14303f56d67e408d7
      - name: 3.9.3
        path: 3.9.3/dragen-wgs-qc-pipeline__3.9.3.cwl
        md5sum: fcd42d588dc19c05ca5920d96717f7f4
    categories:
      - dragen
  - name: tso500-ctdna-post-processing-pipeline
    path: tso500-ctdna-post-processing-pipeline
    versions:
      - name: 1.0.0
        path: 1.0.0/tso500-ctdna-post-processing-pipeline__1.0.0.cwl
        md5sum: a4a744e417933899c13b79a786e3bd45
    categories:
      - tso500
  - name: umccrise-pipeline
    path: umccrise-pipeline
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/umccrise-pipeline__1.2.1--0.cwl
        md5sum: 6100f32cc0c1ecf82da6ea0da96f8622
      - name: 1.2.2--0
        path: 1.2.2--0/umccrise-pipeline__1.2.2--0.cwl
        md5sum: 54fb347935cbbf36c5a36b7e4df6240d
    categories: []
  - name: tso500-ctdna-with-post-processing-pipeline
    path: tso500-ctdna-with-post-processing-pipeline
    versions:
      - name: 1.1.0--1.0.0
        path: 1.1.0--1.0.0/tso500-ctdna-with-post-processing-pipeline__1.1.0--1.0.0.cwl
        md5sum: 27074c377d6c3e7f4f347c48a0ff36b1
    categories:
      - tso500
  - name: umccrise-pipeline
    path: umccrise-pipeline
    versions:
      - name: 1.2.1--0
        path: 1.2.1--0/umccrise-pipeline__1.2.1--0.cwl
        md5sum: 6100f32cc0c1ecf82da6ea0da96f8622
      - name: 1.2.2--0
        path: 1.2.2--0/umccrise-pipeline__1.2.2--0.cwl
        md5sum: 54fb347935cbbf36c5a36b7e4df6240d
    categories: []
  - name: umccrise-with-dragen-germline-pipeline
    path: umccrise-with-dragen-germline-pipeline
    versions:
      - name: 2.0.0--3.9.3
        path: 2.0.0--3.9.3/umccrise-with-dragen-germline-pipeline__2.0.0--3.9.3.cwl
        md5sum: bc5f5fc4be45d8eaf6a44ca844803274
    categories: []
